apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tmc-cas.fullname" . }}
  labels:
    {{- include "tmc-cas.labels" . | nindent 4 }}
spec:
  type: Opaque
  data:
    TMC_API_TOKEN: {{  required "Missing .Values.secret.tmc_api_token. It should be set to TMC API token "  .Values.secret.tmc_api_token }}

